#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "karadav"
name = "KaraDAV"
description.en = "A very lightweight WebDAV server compatible with ownCloud and NextCloud clients"
description.fr = "Un server WebDAV très léger compatible avec les applications ownCloud et NextCloud"

version = "0.4.6~ynh1"

maintainers = [ "OniriCorpe" ]

[upstream]
license = "AGPL-3.0-only"
website = ""
demo = ""
admindoc = "https://github.com/kd2org/karadav/blob/main/README.md"
userdoc = "https://github.com/kd2org/karadav/blob/main/README.md"
code = "https://github.com/kd2org/karadav/"
fund = "https://kd2.org/soutien"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = true
sso = false

disk = "1M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/webdav"

[resources]
    [resources.sources]
        [resources.sources.main]
        url = "https://github.com/kd2org/karadav/archive/refs/tags/0.4.6.tar.gz"
        sha256 = "6f1e28252a198a608c59dd083ca54198cd440e1984918f4412f30a5cc8fa8ef5"
        in_subdir = true
        autoupdate.strategy = "latest_github_tag"

[resources.system_user]

[resources.install_dir]

[resources.data_dir]

# the app doesn't make sense at all if its not public
[resources.permissions]
main.url = "/"
main.allowed = [ "visitors", "all_users" ]
main.protected = true

[resources.apt]
packages = "php8.2-sqlite3, php8.2-simplexml"
