#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "karadav"
name = "KaraDAV"
description.en = "A very lightweight WebDAV server compatible with ownCloud and NextCloud clients"
description.fr = "Un server WebDAV très léger compatible avec les applications ownCloud et NextCloud"

version = "0.4.4~ynh1"

maintainers = [ "OniriCorpe" ]

[upstream]
license = "AGPL-3.0-only"
website = ""
demo = ""
admindoc = "https://github.com/kd2org/karadav/blob/main/README.md"
userdoc = "https://github.com/kd2org/karadav/blob/main/README.md"
code = "https://github.com/kd2org/karadav/"
fund = "https://kd2.org/soutien"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = true

# FIXME: replace with true, false, or "not_relevant".
# Not to confuse with the "ldap" key: the "sso" key corresponds to wether or not a user is *automatically logged-in*
# on the app when logged-in on the YunoHost portal.
sso = "?"

disk = "1M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/dav"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources]
        [resources.sources.main]
        url = "https://github.com/kd2org/karadav/archive/refs/tags/0.4.4.tar.gz"
        sha256 = "ae4896cd03af3099548272716877b3e072cbb216b2a0f80b5114314d475d56a0"
        in_subdir = true
        autoupdate.strategy = "latest_github_tag"

[resources.system_user]

[resources.install_dir]

[resources.data_dir]

[resources.permissions]
main.url = "/"

[resources.apt]
packages = "php8.2-sqlite3, php8.2-simplexml"
