#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "karadav"
name = "KaraDAV"
description.en = "WebDAV server compatible with ownCloud and NextCloud"
description.fr = "Server WebDAV compatible avec ownCloud et NextCloud"

version = "0.7.1~ynh1"

maintainers = [ "OniriCorpe" ]

[upstream]
license = "AGPL-3.0-only"
admindoc = "https://github.com/kd2org/karadav/blob/main/README.md"
userdoc = "https://github.com/kd2org/karadav/blob/main/README.md"
code = "https://github.com/kd2org/karadav/"
fund = "https://kd2.org/soutien"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = true
sso = false

disk = "100M"
ram.build = "150M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/karadav"

[resources]

    [resources.sources]

        [resources.sources.main]
        in_subdir = true
        url = "https://github.com/kd2org/karadav/archive/refs/tags/0.7.0-beta1.tar.gz"
        sha256 = "723a2c473c5831e955147c6b1d3b911ed91fdd27415cb25522095b24345635d6"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    main.allowed = [ "visitors" ]

    [resources.apt]
    packages = "php8.4-sqlite3, php8.4-simplexml, php8.4-imagick"
