#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

# the app doesn't make sense at all if its not public
exclude = [ "install.private" ]
