#!/bin/bash

source /usr/share/yunohost/helpers

ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

ynh_script_progression "Change of URL completed for $app"
