#!/bin/bash

## this script is only run if actual change to domain/path is detected, if you're here either $domain or $path changed
## new location is available via $domain and $path (or $new_domain and $new_path variables if you want to be explicit)
## old values are available via, you guessed it, $old_domain and $old_path

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STANDARD MODIFICATIONS
#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression --message="Updating NGINX web server configuration..." --weight=1

ynh_change_url_nginx_config

#=================================================
# SPECIFIC MODIFICATIONS
#=================================================
# MODIFY URL IN the KARADAV CONF
#=================================================
ynh_script_progression --message="Updating KaraDAV configuration..." --weight=1

path_without_trailing_slash=${path%/}
ynh_write_var_in_file --file="$install_dir/config.local.conf" --key=WWW_URL --value="$domain$path_without_trailing_slash/"
ynh_store_file_checksum --file="$install_dir/config.local.conf"

#=================================================
# GENERIC FINALISATION
#=================================================

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Change of URL completed for $app" --last
