#!/bin/bash

source /usr/share/yunohost/helpers

# import needed settings
php_version=$(ynh_app_setting_get --key=php_version)

#=================================================
# SPECIFIC GETTERS
#=================================================

get__wopi_url() {
    local get_wopi_url
    get_wopi_url=$(ynh_read_var_in_file --file="$install_dir/config.local.php" --key=WOPI_DISCOVERY_URL)
    if [[ $get_wopi_url == "null" ]]; then
        echo ""
    else
        echo "$get_wopi_url"
    fi
}

#=================================================
# SPECIFIC SETTERS
#=================================================

set__wopi_url() {

    # the variable must be 'null' if the setting is not used
    if [[ $wopi_url == "" ]]; then
        wopi_url="null"
    fi

    # update karadav config
    ynh_write_var_in_file --file="$install_dir/config.local.php" --key=WOPI_DISCOVERY_URL --value="$wopi_url"
    ynh_store_file_checksum "$install_dir/config.local.php"

    # save updated setting
    ynh_app_setting_set --key=wopi_url --value="$wopi_url"

}

# Keep this last line
ynh_app_config_run "$1"