#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_app_setting_set --key=php_upload_max_filesize --value=__UPLOAD_MAX_FILESIZE__

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

secret_key="$(ynh_string_random --length=30)"
upload_max_filesize="1G"
post_max_size="1G"
wopi_url="null"

ynh_app_setting_set --key=secret_key --value="$secret_key"
ynh_app_setting_set --key=upload_max_filesize --value="$upload_max_filesize"
ynh_app_setting_set --key=post_max_size --value="$post_max_size"
ynh_app_setting_set --key=wopi_url --value="$wopi_url"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a PHP-FPM config (with conf/extra_php-fpm.conf being appended to it)
ynh_config_add_phpfpm

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

yunohost service add "$app" --description="KaraDAV, WebDAV server" --log="/var/log/$app/$app.log"

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding app configuration file..."

ynh_config_add --template="config.local.php" --destination="$install_dir/config.local.php"

#=================================================
# SECURE FILES AND DIRECTORIES
#=================================================

# Fix app ownerships & permissions
# borrowed here https://github.com/YunoHost-Apps/nextcloud_ynh/blob/master/scripts/install#L223
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R "$app:www-data" "$install_dir"
chown -R "$app:" "$data_dir"
find "$data_dir" -type f -print0 | xargs -r0 chmod 0640
find "$data_dir" -type d -print0 | xargs -r0 chmod 0750
chmod 755 /home/yunohost.app
#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod 400 "$install_dir/config.local.php"
#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown "$app:$app" "$install_dir/config.local.php"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
